// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package portal

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message_Type int32

const (
	Message_HTTP_CONNECT             Message_Type = 0
	Message_HTTP_CONNECT_OK          Message_Type = 1
	Message_HTTP_SERVICE_UNAVAILABLE Message_Type = 2
	Message_DISCONNECTED             Message_Type = 3
	Message_DATA                     Message_Type = 4
)

var Message_Type_name = map[int32]string{
	0: "HTTP_CONNECT",
	1: "HTTP_CONNECT_OK",
	2: "HTTP_SERVICE_UNAVAILABLE",
	3: "DISCONNECTED",
	4: "DATA",
}

var Message_Type_value = map[string]int32{
	"HTTP_CONNECT":             0,
	"HTTP_CONNECT_OK":          1,
	"HTTP_SERVICE_UNAVAILABLE": 2,
	"DISCONNECTED":             3,
	"DATA":                     4,
}

func (x Message_Type) String() string {
	return proto.EnumName(Message_Type_name, int32(x))
}

func (Message_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0, 0}
}

type Message_Origin int32

const (
	Message_ORIGIN_LOCAL  Message_Origin = 0
	Message_ORIGIN_REMOTE Message_Origin = 1
)

var Message_Origin_name = map[int32]string{
	0: "ORIGIN_LOCAL",
	1: "ORIGIN_REMOTE",
}

var Message_Origin_value = map[string]int32{
	"ORIGIN_LOCAL":  0,
	"ORIGIN_REMOTE": 1,
}

func (x Message_Origin) String() string {
	return proto.EnumName(Message_Origin_name, int32(x))
}

func (Message_Origin) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0, 1}
}

type Message struct {
	Type                 Message_Type   `protobuf:"varint,1,opt,name=type,proto3,enum=portal.Message_Type" json:"type,omitempty"`
	Origin               Message_Origin `protobuf:"varint,2,opt,name=origin,proto3,enum=portal.Message_Origin" json:"origin,omitempty"`
	Id                   int32          `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	SocketAddress        string         `protobuf:"bytes,4,opt,name=socket_address,json=socketAddress,proto3" json:"socket_address,omitempty"`
	Buf                  []byte         `protobuf:"bytes,5,opt,name=buf,proto3" json:"buf,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetType() Message_Type {
	if m != nil {
		return m.Type
	}
	return Message_HTTP_CONNECT
}

func (m *Message) GetOrigin() Message_Origin {
	if m != nil {
		return m.Origin
	}
	return Message_ORIGIN_LOCAL
}

func (m *Message) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Message) GetSocketAddress() string {
	if m != nil {
		return m.SocketAddress
	}
	return ""
}

func (m *Message) GetBuf() []byte {
	if m != nil {
		return m.Buf
	}
	return nil
}

func init() {
	proto.RegisterEnum("portal.Message_Type", Message_Type_name, Message_Type_value)
	proto.RegisterEnum("portal.Message_Origin", Message_Origin_name, Message_Origin_value)
	proto.RegisterType((*Message)(nil), "portal.Message")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xcd, 0x4e, 0x84, 0x30,
	0x10, 0xc7, 0xb7, 0x2c, 0x8b, 0x3a, 0x59, 0xb0, 0x56, 0x63, 0x7a, 0xf0, 0x40, 0x48, 0x4c, 0xb8,
	0xc8, 0x41, 0x9f, 0xa0, 0x42, 0xa3, 0x44, 0x96, 0x9a, 0x6e, 0xdd, 0x2b, 0x61, 0xa5, 0x12, 0xe2,
	0x07, 0x04, 0xf0, 0xb0, 0xef, 0xe7, 0x83, 0x19, 0x3e, 0x0e, 0xc6, 0xdb, 0xe4, 0xf7, 0xff, 0xcd,
	0x64, 0x66, 0xc0, 0xfe, 0xd4, 0x5d, 0x97, 0x97, 0x3a, 0x68, 0xda, 0xba, 0xaf, 0x89, 0xd5, 0xd4,
	0x6d, 0x9f, 0x7f, 0x78, 0x3f, 0x06, 0x1c, 0x6d, 0xa6, 0x84, 0xf8, 0x60, 0xf6, 0x87, 0x46, 0x53,
	0xe4, 0x22, 0xdf, 0xb9, 0xbd, 0x08, 0x26, 0x25, 0x98, 0xe3, 0x40, 0x1d, 0x1a, 0x2d, 0x47, 0x83,
	0x04, 0x60, 0xd5, 0x6d, 0x55, 0x56, 0x5f, 0xd4, 0x18, 0xdd, 0xcb, 0xff, 0xae, 0x18, 0x53, 0x39,
	0x5b, 0xc4, 0x01, 0xa3, 0x2a, 0xe8, 0xd2, 0x45, 0xfe, 0x4a, 0x1a, 0x55, 0x41, 0xae, 0xc1, 0xe9,
	0xea, 0xd7, 0x77, 0xdd, 0x67, 0x79, 0x51, 0xb4, 0xba, 0xeb, 0xa8, 0xe9, 0x22, 0xff, 0x44, 0xda,
	0x13, 0x65, 0x13, 0x24, 0x18, 0x96, 0xfb, 0xef, 0x37, 0xba, 0x72, 0x91, 0xbf, 0x96, 0x43, 0xe9,
	0x95, 0x60, 0x0e, 0x6b, 0x10, 0x0c, 0xeb, 0x47, 0xa5, 0x9e, 0xb3, 0x50, 0xa4, 0x29, 0x0f, 0x15,
	0x5e, 0x90, 0x73, 0x38, 0xfd, 0x4b, 0x32, 0xf1, 0x84, 0x11, 0xb9, 0x02, 0x3a, 0xc2, 0x2d, 0x97,
	0xbb, 0x38, 0xe4, 0xd9, 0x4b, 0xca, 0x76, 0x2c, 0x4e, 0xd8, 0x7d, 0xc2, 0xb1, 0x31, 0x0c, 0x89,
	0xe2, 0xed, 0xdc, 0xc0, 0x23, 0xbc, 0x24, 0xc7, 0x60, 0x46, 0x4c, 0x31, 0x6c, 0x7a, 0x37, 0x60,
	0x4d, 0x37, 0x0c, 0x96, 0x90, 0xf1, 0x43, 0x9c, 0x66, 0x89, 0x08, 0x59, 0x82, 0x17, 0xe4, 0x0c,
	0xec, 0x99, 0x48, 0xbe, 0x11, 0x8a, 0x63, 0xb4, 0xb7, 0xc6, 0xaf, 0xde, 0xfd, 0x06, 0x00, 0x00,
	0xff, 0xff, 0x86, 0xec, 0xfb, 0xff, 0x66, 0x01, 0x00, 0x00,
}
